version: 2

build:
  image: stable
  apt_packages:
    - libatlas-base-dev
    - python3.7-dev
    - python3-wheel
    - doxygen
    - graphviz

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - requirements: python/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
