version: 2

build:
  image: latest
  apt_packages:
    - cmake
    - doxygen
    - graphviz
    - libblas-dev
    - python3.7-dev
    - python3-wheel

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - requirements: python/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
