name: Documentation
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "include/**"

jobs:
  build:
    name: Build (HTML)
    runs-on: ubuntu-20.04

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: sudo apt install -y libopenblas-dev python3.8-dev doxygen graphviz

      - name: Install Python dependencies
        run: |
          cd python
          make dist
          pip3 install ../dist/*.whl
          pip3 install -r docs/requirements.txt

      - name: Generate documentation
        run: make docs

      - name: Upload HTML
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: docs/_build/html/