name: Format
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "include/**"
      - "python/**"
      - "test/**"

jobs:
  format-cpp:
    name: C++
    runs-on: ubuntu-20.04

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Install dependencies
        run: sudo apt update && sudo apt -y install clang-format python3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run formatter
        run: ./bin/format --check include python/src test

  format-python:
    name: Python
    runs-on: ubuntu-20.04

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Install dependencies
        run: sudo apt update && sudo apt -y install python3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create virtual environment
        run: |
          cd python
          make setup

      - name: Run formatter
        run: |
          cd python
          make format check=1