name: Format
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "include/**"
      - "src/**"
      - "test/**"

jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Install dependencies
        run: sudo apt update && sudo apt -y install clang-format python3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run formatter
        run: ./bin/format --check include src test