name: Python
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.rst"

jobs:
  test-ubuntu:
    name: Build (Python) on Ubuntu
    runs-on: ubuntu-20.04

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Install dependencies
        run: sudo apt install -y libopenblas-dev python3.8-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd python
          make test args="-o junit_family=xunit2 --junitxml=report.xml"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ubuntu-test-report
          path: python/report.xml

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Test Report (Python) on Ubuntu
          files: python/report.xml

  test-macos:
    name: Build (Python) on MacOS
    runs-on: macos-10.15

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Install dependencies
        run: brew install libomp

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd python
          make test args="-o junit_family=xunit2 --junitxml=report.xml"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: macos-test-report
          path: python/report.xml