name: Build-wheels
env:
  CIBW_SKIP: cp27-* cp35-* cp36-*
  CIBW_ARCHS: auto64
  CIBW_BEFORE_ALL_LINUX: yum install -y openblas-devel
  CIBW_BEFORE_BUILD: pip install "cmake>=3.14"
on:
  pull_request:
  push:
    branches:
      - main
      - cibuild
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.rst"
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl