name: Wheels
on:
  release:
  workflow_dispatch:
  push:

jobs:
  build-wheels:
    name: Build wheels for cp${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] #[ubuntu-latest, macos-latest, windows-latest]
        python: [39] #[37, 38, 39]
        include:
          - os: windows-latest
        #include:
          #- os: ubuntu-latest
           # cibw_before_all: yum install -y openblas-devel
            #cibw_environment: CBLAS_ROOT=/usr/include/openblas 
          #- os: macos-latest
           # cibw_environment: MACOSX_DEPLOYMENT_TARGET=10.14 # Required for C++17 support
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: auto64 # Only build for 64-bit platforms
          CIBW_BUILD: cp${{ matrix.python }}-*
          CIBW_BEFORE_BUILD: pip install "cmake>=3.14"
          CIBW_BEFORE_ALL: ${{ matrix.cibw_before_all }}
          CIBW_ENVIRONMENT: ${{ matrix.cibw_environment }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "python -m pytest {project}/python/tests -W ignore::UserWarning"
      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl